package dev.jasonpearson.automobile.desktop.core.daemon

import java.io.File
import java.util.concurrent.CopyOnWriteArrayList
import kotlinx.serialization.json.JsonArray
import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.JsonNull
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.JsonPrimitive
import kotlinx.serialization.json.booleanOrNull
import kotlinx.serialization.json.contentOrNull
import kotlinx.serialization.json.doubleOrNull
import kotlinx.serialization.json.intOrNull
import kotlinx.serialization.json.jsonArray
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive

/**
 * Desktop <-> daemon wire fixtures (#10669): request/response pairs the REAL daemon handlers
 * produced for the frames this client sends, generated by `test/daemon/desktopWireContract.test.ts`
 * into `test/fixtures/desktop-wire/` at the repo root. Regenerate them there; never edit by hand.
 */
internal class DesktopWireFixture(val scenario: String, private val root: JsonObject) {

  /** Session UUIDs by role: `desktop-1`, `desktop-2` (in the order the client mints them), ... */
  val sessions: Map<String, String> =
    root.getValue("sessions").jsonObject.mapValues { it.value.jsonPrimitive.content }

  val exchanges: List<WireExchange> =
    root.getValue("exchanges").jsonArray.map { WireExchange(it.jsonObject) }

  /** The frames the desktop client sends, in order, with each `repeat` run expanded. */
  val desktopFrames: List<WireExchange>
    get() =
      exchanges
        .filter { it.actor == "desktop" }
        .flatMap { exchange -> List(exchange.repeat) { exchange } }

  fun exchange(label: String): WireExchange =
    exchanges.singleOrNull { it.label == label }
      ?: error("Fixture $scenario has no single exchange labelled '$label'")

  /** Ticks in the heartbeat run labelled [label]. */
  fun ticks(label: String): Int = exchange(label).repeat

  companion object {
    private const val FIXTURE_DIR = "test/fixtures/desktop-wire"

    private val cache = java.util.concurrent.ConcurrentHashMap<String, DesktopWireFixture>()

    fun load(scenario: String): DesktopWireFixture =
      cache.getOrPut(scenario) {
        val relative = "$FIXTURE_DIR/$scenario.json"
        val file =
          generateSequence(File(System.getProperty("user.dir") ?: ".").absoluteFile) {
              it.parentFile
            }
            .map { File(it, relative) }
            .firstOrNull { it.isFile } ?: error("Could not locate $relative")
        DesktopWireFixture(scenario, DaemonJson.parseToJsonElement(file.readText()).jsonObject)
      }
  }
}

internal class WireExchange(private val json: JsonObject) {
  val actor: String = json.getValue("actor").jsonPrimitive.content
  val label: String = json.getValue("label").jsonPrimitive.content
  val repeat: Int = json["repeat"]?.jsonPrimitive?.intOrNull ?: 1
  private val request = json.getValue("request").jsonObject
  val method: String = request.getValue("method").jsonPrimitive.content
  val params: JsonObject = request.getValue("params").jsonObject
  private val response = json.getValue("response").jsonObject

  /** The daemon's socket answer to this frame, re-addressed to [requestId]. */
  fun response(requestId: String): DaemonResponse =
    DaemonResponse(
      id = requestId,
      type = "mcp_response",
      success = response.getValue("success").jsonPrimitive.booleanOrNull == true,
      result = response["result"]?.takeUnless { it is JsonNull },
      error = response["error"]?.jsonPrimitive?.contentOrNull,
      code = response["code"] as? JsonPrimitive,
      releaseReason = response["releaseReason"]?.jsonPrimitive?.contentOrNull,
    )

  /** The `result` envelope (a tool result for `tools/call`). */
  val result: JsonElement
    get() = requireNotNull(response["result"]) { "Exchange '$label' has no result" }

  /** The first text content of a tool result. */
  val toolText: String
    get() =
      result.jsonObject
        .getValue("content")
        .jsonArray
        .first()
        .jsonObject
        .getValue("text")
        .jsonPrimitive
        .content

  fun matches(request: DaemonRequest): Boolean =
    request.method == method && sameJson(request.params, params)
}

/**
 * Replays one fixture's desktop frames in order: every request must be the next recorded desktop
 * frame (method and params), and is answered with the daemon's recorded response. Agent and probe
 * exchanges are daemon-side context and are skipped.
 */
internal class FixtureReplayDaemonTransport(private val fixture: DesktopWireFixture) :
  DaemonRequestTransport {
  private val expected = fixture.desktopFrames
  private val sent = CopyOnWriteArrayList<DaemonRequest>()
  private val mismatches = CopyOnWriteArrayList<String>()

  /** Labels of the recorded frames answered so far. */
  val answeredLabels: List<String>
    get() = expected.take(sent.size).map { it.label }

  override fun send(request: DaemonRequest): DaemonResponse {
    val index = sent.size
    sent.add(request)
    val frame = expected.getOrNull(index)
    if (frame == null || !frame.matches(request)) {
      mismatches +=
        "frame ${index + 1}: client sent ${request.method} ${request.params}, fixture " +
          (frame?.let { "recorded '${it.label}' ${it.method} ${it.params}" }
            ?: "has no more frames")
      return DaemonResponse(
        id = request.id,
        type = "mcp_response",
        success = false,
        error = "Frame not in fixture ${fixture.scenario}",
      )
    }
    return frame.response(request.id)
  }

  /**
   * The client sent exactly the recorded desktop frames up to and including the last frame labelled
   * [throughLabel] (all of them when null).
   */
  fun assertReplayed(throughLabel: String? = null) {
    check(mismatches.isEmpty()) {
      "Client frames diverged from fixture ${fixture.scenario}:\n" + mismatches.joinToString("\n")
    }
    val through =
      throughLabel?.let { label -> expected.indexOfLast { it.label == label } + 1 } ?: expected.size
    check(through > 0) { "Fixture ${fixture.scenario} has no desktop frame '$throughLabel'" }
    check(sent.size == through) {
      "Expected ${fixture.scenario} replayed through frame $through " +
        "(${expected[through - 1].label}); the client sent ${sent.size} frames: $answeredLabels"
    }
  }
}

/** JSON equality that treats `540` and `540.0` as the same number (Kotlin sends doubles). */
private fun sameJson(a: JsonElement, b: JsonElement): Boolean =
  when {
    a is JsonObject && b is JsonObject ->
      a.keys == b.keys && a.keys.all { key -> sameJson(a.getValue(key), b.getValue(key)) }
    a is JsonArray && b is JsonArray -> a.size == b.size && a.indices.all { sameJson(a[it], b[it]) }
    a is JsonPrimitive && b is JsonPrimitive ->
      if (!a.isString && !b.isString && a.doubleOrNull != null && b.doubleOrNull != null) {
        a.doubleOrNull == b.doubleOrNull
      } else {
        a == b
      }
    else -> a == b
  }
