package dev.jasonpearson.automobile.validation

/**
 * Tool names accepted in plan YAML `tool:` steps. Keep in sync with MCP `ToolRegistry` /
 * `schemas/tool-definitions.json` (and legacy aliases still used in plans).
 */
object ValidTools {
  /**
   * Legacy tool names that `PlanMigrator` rewrites to `sendKeys`, so plans using them still run.
   * All other names must exist in `schemas/tool-definitions.json` (enforced by `ValidToolsTest`).
   */
  val MIGRATED_LEGACY_TOOLS = setOf("clearText", "imeAction", "inputText")

  val TOOLS =
    MIGRATED_LEGACY_TOOLS +
      setOf(
        "accessibility",
        "accessibilityFocus",
        "barrier",
        "biometricAuth",
        "changeLocalization",
        "clearKeyValueFile",
        "clearMockNetwork",
        "clipboard",
        "crashApp",
        "criticalSection",
        "deviceSnapshot",
        "dragAndDrop",
        "executePlan",
        "explore",
        "exportPlan",
        "getAppPermissions",
        "getDeepLinks",
        "getDeviceState",
        "getNavigationGraph",
        "getNetworkGraph",
        "getNotificationPolicy",
        "highlight",
        "homeScreen",
        "identifyInteractions",
        "installApp",
        "keyboard",
        "killDevice",
        "launchApp",
        "listApps",
        "listDeviceImages",
        "listDevices",
        "mockNetwork",
        "navigateTo",
        "network",
        "observe",
        "openLink",
        "pinchOn",
        "postNotification",
        "pressButton",
        "provisionDevice",
        "recentApps",
        "recordSteps",
        "removeKeyValue",
        "rotate",
        "selectAllText",
        "sendKeys",
        "setActiveDevice",
        "setAppPermissions",
        "setDeviceState",
        "setKeyValue",
        "setNotificationPolicy",
        "setUIState",
        "shake",
        "sqlQuery",
        "putAppFile",
        "startTestRecording",
        "swipeOn",
        "systemTray",
        "tapOn",
        "deleteDevice",
        "terminateApp",
        "uninstallApp",
        "videoRecording",
        "appLifecycle",
        "displayConfig",
        "getAndroid",
        "getApple",
        "getDataStore",
        "getIosSimulatorCapabilities",
        "getPreference",
        "hitTest",
        "listDataStores",
        "prototype",
        "phoneCall",
        "resetAppLogs",
        "resetKeychain",
        "sendSms",
        "setDeviceResources",
        "setPosture",
        "setPreference",
        "setToolEnabled",
        "snapshotOf",
        "stageSessionDownloads",
        "tapAny",
        "tapAt",
        "wakeAndUnlock",
      )

  val DEPRECATED_FIELDS = setOf("generated", "appId", "parameters", "description")
}
