package dev.jasonpearson.automobile.validation

/**
 * Tool names accepted in plan YAML `tool:` steps: every tool in `schemas/tool-definitions.json`
 * plus [LEGACY_MIGRATED_TOOLS]. `ValidToolsTest` fails when this list drifts from that file.
 */
object ValidTools {
  /** Names the TypeScript `PlanMigrator` renames to `sendKeys`; they are not registry tools. */
  val LEGACY_MIGRATED_TOOLS = setOf("clearText", "imeAction", "inputText")

  /** Tools in `schemas/tool-definitions.json`. */
  val REGISTRY_TOOLS =
    setOf(
      "accessibility",
      "accessibilityFocus",
      "appLifecycle",
      "barrier",
      "biometricAuth",
      "changeLocalization",
      "clearKeyValueFile",
      "clearMockNetwork",
      "clipboard",
      "crashApp",
      "criticalSection",
      "deleteDevice",
      "deviceSnapshot",
      "displayConfig",
      "dragAndDrop",
      "executePlan",
      "explore",
      "exportPlan",
      "getAndroid",
      "getAppPermissions",
      "getApple",
      "getDataStore",
      "getDeepLinks",
      "getDeviceState",
      "getIosSimulatorCapabilities",
      "getNavigationGraph",
      "getNetworkGraph",
      "getNotificationPolicy",
      "getPreference",
      "highlight",
      "hitTest",
      "homeScreen",
      "identifyInteractions",
      "installApp",
      "keyboard",
      "killDevice",
      "launchApp",
      "listApps",
      "listDataStores",
      "listDeviceImages",
      "listDevices",
      "mockNetwork",
      "navigateTo",
      "network",
      "observe",
      "openLink",
      "overlay",
      "phoneCall",
      "pinchOn",
      "postNotification",
      "pressButton",
      "provisionDevice",
      "putAppFile",
      "recentApps",
      "recordSteps",
      "removeKeyValue",
      "resetAppLogs",
      "resetKeychain",
      "rotate",
      "selectAllText",
      "sendKeys",
      "sendSms",
      "setActiveDevice",
      "setAppPermissions",
      "setDeviceResources",
      "setDeviceState",
      "setKeyValue",
      "setNotificationPolicy",
      "setPosture",
      "setPreference",
      "setToolEnabled",
      "setUIState",
      "shake",
      "snapshotOf",
      "sqlQuery",
      "stageSessionDownloads",
      "startTestRecording",
      "swipeOn",
      "systemTray",
      "tapAny",
      "tapAt",
      "tapOn",
      "terminateApp",
      "uninstallApp",
      "videoRecording",
      "wakeAndUnlock",
    )

  val TOOLS = REGISTRY_TOOLS + LEGACY_MIGRATED_TOOLS

  val DEPRECATED_FIELDS = setOf("generated", "appId", "parameters", "description")
}
