package dev.jasonpearson.automobile.desktop.core.video

import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue

/**
 * Decodes a real H.264 Annex-B sample (320x240, generated by ffmpeg) end to end.
 *
 * This is the load-bearing test for the live device view: it proves the bundled ffmpeg natives
 * resolve on this platform, that a raw elementary stream decodes without a container, and that
 * frames come out as tightly packed BGRA that Skia can consume.
 */
class H264DecoderTest {

  private fun sample(): ByteArray =
    checkNotNull(javaClass.classLoader.getResourceAsStream("sample.h264")) {
        "sample.h264 missing from test resources"
      }
      .use { it.readBytes() }

  @Test
  fun `decodes a raw annex-b stream into frames`() {
    val frames = mutableListOf<Pair<Int, Int>>()

    H264Decoder().use { decoder -> decoder.decode(sample()) { frames.add(it.width to it.height) } }

    assertTrue(frames.isNotEmpty(), "expected at least one decoded frame")
    assertEquals(320 to 240, frames.first(), "frame dimensions come from the in-band SPS")
  }

  @Test
  fun `frame buffers are tightly packed BGRA`() {
    var seen: DecodedFrame? = null

    H264Decoder().use { decoder ->
      decoder.decode(sample()) { frame ->
        if (seen == null) seen = DecodedFrame(frame.width, frame.height, frame.bgra.copyOf())
      }
    }

    val frame = checkNotNull(seen)
    // 4 bytes per pixel with no row padding is what Skia's BGRA_8888 expects.
    assertEquals(frame.width * frame.height * 4, frame.bgra.size)
  }

  @Test
  fun `a stream split across arbitrary chunk boundaries decodes the same`() {
    // The relay hands over whatever the capture source produced; chunks do not align to frames.
    val whole = mutableListOf<Pair<Int, Int>>()
    H264Decoder().use { d -> d.decode(sample()) { whole.add(it.width to it.height) } }

    val chunked = mutableListOf<Pair<Int, Int>>()
    H264Decoder().use { decoder ->
      sample().asIterable().chunked(1000) { chunk ->
        decoder.decode(chunk.toByteArray()) { chunked.add(it.width to it.height) }
      }
    }

    assertEquals(whole, chunked, "chunking must not change the decoded frame sequence")
  }

  @Test
  fun `an empty chunk is a no-op`() {
    H264Decoder().use { decoder ->
      decoder.decode(ByteArray(0)) { error("no frame should be produced") }
    }
  }

  @Test
  fun `garbage does not throw, since the next key frame resynchronises`() {
    H264Decoder().use { decoder ->
      decoder.decode(ByteArray(64) { 0xAB.toByte() }) {
        // May legitimately produce nothing; the point is that it does not blow up.
      }
    }
  }

  @Test
  fun `decoding after close is rejected`() {
    val decoder = H264Decoder()
    decoder.close()

    var threw = false
    try {
      decoder.decode(sample()) {}
    } catch (_: IllegalStateException) {
      threw = true
    }
    assertTrue(threw, "a closed decoder must not be usable")
  }

  @Test
  fun `close is idempotent`() {
    val decoder = H264Decoder()
    decoder.close()
    decoder.close()
  }
}
