#!/usr/bin/env bun
//
// Generate the browser JavaScript served by the MkDocs site from its TypeScript
// sources. The docs assets (download charts, copyable-prompt UI) are authored in
// docs-assets/src/*.ts and emitted to docs/assets/javascripts/*.js, which the
// site references via mkdocs.yml's `extra_javascript`. The emitted .js is checked
// in — the GitHub Pages deploy (scripts/github/deploy_pages.py) runs on a
// Python/uv toolchain with no Bun, so it consumes the committed output directly.
//
// This uses Bun's built-in bundler and oxfmt (both already in the toolchain), so
// no new dependency is introduced. See docs-assets/README.md.
//
// Usage:
//   bun scripts/docs/build-docs-assets.ts           # regenerate the .js
//   bun scripts/docs/build-docs-assets.ts --check    # fail if committed .js is stale
//
// The --check mode is the CI gate (registered in all_fast_validate_checks.sh):
// it rebuilds into memory and diffs against the committed output so a hand-edit
// of the generated .js, or a source change that was not rebuilt, is rejected.

import { spawnSync } from "child_process";
import { readFileSync } from "fs";
import { join } from "path";

const ROOT = join(import.meta.dir, "..", "..");
const SRC_DIR = join(ROOT, "docs-assets", "src");
const OUT_DIR = join(ROOT, "docs", "assets", "javascripts");
const TSCONFIG = join(ROOT, "docs-assets", "tsconfig.json");

// Entry basename -> emitted file. Keep in sync with mkdocs.yml extra_javascript.
const ENTRIES = ["prompt-form", "usage-data"];

const BANNER =
  "// @generated by scripts/docs/build-docs-assets.ts from docs-assets/src/" +
  "$NAME$.ts.\n// Do not edit this file directly; edit the TypeScript source and " +
  "rebuild.\n";

function fail(message: string): never {
  console.error(`error: ${message}`);
  process.exit(1);
}

// Type-check the browser sources against their DOM-scoped tsconfig. Bun's
// bundler transpiles without checking types, so this is the only type gate for
// the docs assets; a failure here means the source, not the emitted output.
function typecheck(): void {
  const result = spawnSync("bunx", ["tsgo", "--noEmit", "-p", TSCONFIG], {
    cwd: ROOT,
    stdio: "inherit",
  });
  if (result.status !== 0) {
    fail("docs-assets TypeScript failed type-checking (see tsgo output above)");
  }
}

// Bundle one entry into browser IIFE JavaScript, format it with oxfmt, and
// prepend the generated banner. Returns the exact bytes that belong on disk.
async function buildOne(name: string): Promise<string> {
  const built = await Bun.build({
    entrypoints: [join(SRC_DIR, `${name}.ts`)],
    target: "browser",
    format: "iife",
    minify: false,
    sourcemap: "none",
  });
  if (!built.success) {
    for (const log of built.logs) {
      console.error(log);
    }
    fail(`bundling docs-assets/src/${name}.ts failed`);
  }
  if (built.outputs.length !== 1) {
    fail(`expected one output for ${name}, got ${built.outputs.length}`);
  }
  const bundled = await built.outputs[0].text();
  // Prepend the banner and format the whole file with the repo formatter (oxfmt)
  // so the checked-in bytes are a true oxfmt fixpoint. oxfmt scans
  // docs/assets/javascripts/*.js in format:check, so the emitted output — banner
  // included — must already be oxfmt-clean and stable across rebuilds.
  const banner = BANNER.replace("$NAME$", name);
  const formatted = spawnSync("bunx", ["oxfmt", "--stdin-filepath", `${name}.js`], {
    cwd: ROOT,
    input: banner + bundled,
    encoding: "utf8",
  });
  if (formatted.status !== 0) {
    process.stderr.write(formatted.stderr || "");
    fail(`formatting generated ${name}.js failed`);
  }
  return formatted.stdout;
}

async function main(): Promise<void> {
  const check = process.argv.includes("--check");
  typecheck();

  const stale: string[] = [];
  for (const name of ENTRIES) {
    const contents = await buildOne(name);
    const outPath = join(OUT_DIR, `${name}.js`);
    if (check) {
      let existing = "";
      try {
        existing = readFileSync(outPath, "utf8");
      } catch {
        existing = "";
      }
      if (existing !== contents) {
        stale.push(`docs/assets/javascripts/${name}.js`);
      }
    } else {
      await Bun.write(outPath, contents);
      console.log(`✓ wrote docs/assets/javascripts/${name}.js`);
    }
  }

  if (check && stale.length > 0) {
    fail(
      "generated docs assets are out of date:\n" +
        stale.map((f) => `  - ${f}`).join("\n") +
        "\nRun `bun scripts/docs/build-docs-assets.ts` and commit the result.",
    );
  }
  if (check) {
    console.log("docs assets are up to date.");
  }
}

await main();
