import type { ChildProcess } from "child_process";
import { randomUUID } from "node:crypto";
import { logger } from "../utils/logger";
import { SessionManager } from "./sessionManager";
import { ActionableError, BootedDevice, DeviceInfo, Platform } from "../models";
import { Mutex } from "async-mutex";
import { MultiPlatformDeviceManager, PlatformDeviceManager, waitForDeviceReadyOrCancel } from "../utils/deviceUtils";
import { Timer, defaultTimer } from "../utils/SystemTimer";
import type { InstalledAppsStore } from "../db/installedAppsRepository";
import { InstalledAppsRepository } from "../db/installedAppsRepository";
import { RetryExecutor, defaultRetryExecutor } from "../utils/retry/RetryExecutor";
import { createGlobalPerformanceTracker } from "../utils/PerformanceTracker";
import { isDevicePoolAutolockEnabled, getDevicePoolTimeoutMs } from "./poolConfig";
import { DeviceSessionRepository } from "../db/deviceSessionRepository";
import {
  DeviceCriteriaMatcher,
  DeviceAllocationCriteria,
  DeviceAllocationRequest,
} from "./DeviceCriteriaMatcher";
import { resetAdbDeviceListCache } from "../utils/android-cmdline-tools/AdbClient";
import { consolePortFromSerial } from "../utils/android-cmdline-tools/EmulatorConsoleClient";
import { getInstalledAppsCacheWriteCoordinator } from "../db/installedAppsCacheWriteCoordinator";
import { getDbWriteBarrier } from "../db/dbWriteBarrier";

export type { DeviceAllocationCriteria, DeviceAllocationRequest } from "./DeviceCriteriaMatcher";

/**
 * Error class for device pool operations with retryability flag.
 */
export class DevicePoolError extends Error {
  constructor(
    message: string,
    public readonly isRetryable: boolean
  ) {
    super(message);
    this.name = "DevicePoolError";
  }
}

/**
 * Pooled Device Status
 */
export type DeviceStatus = "idle" | "busy" | "error";

/**
 * Pooled Device
 *
 * Represents a device in the pool with assignment info
 */
export interface PooledDevice {
  id: string;                    // Device ID (e.g., "emulator-5554")
  name: string;                  // Device name (e.g., "Pixel 7")
  platform: Platform;            // Device platform
  sessionId: string | null;      // Session currently using it, null if idle
  status: DeviceStatus;          // Current status
  lastUsedAt: number;            // Last usage timestamp
  assignmentCount: number;       // How many times assigned
  errorCount: number;            // Consecutive errors
  iosVersion?: string;           // iOS version (simulators only)
  simulatorType?: string;        // Simulator type display name (simulators only)
  autolockSessionId?: string;    // Session ID generated by autolock (when enabled)
}

interface IosLivenessSnapshot {
  discoverySucceeded: boolean;
  bootedDeviceIds: Set<string>;
}

type IdleDeviceLivenessStatus = "assignable" | "stale" | "unknown";

interface AssignableIdleDeviceSelection {
  device?: PooledDevice;
  livenessUnknown: boolean;
}

interface DeviceDisconnectSessionReleaser {
  (sessionId: string, deviceId: string, releaseReason: string): Promise<void>;
}

interface DeviceReadyListener {
  (deviceId: string): void;
}

/**
 * Device Pool
 *
 * Manages a pool of Android devices for parallel test execution:
 * - Tracks which devices are available vs assigned to sessions
 * - Ensures each session gets a unique device
 * - Enables multiple tests to run in parallel
 *
 * Works with SessionManager to maintain bidirectional mappings.
 */
export class DevicePool {
  private devices: Map<string, PooledDevice> = new Map();
  private deviceSessionStarts: Map<string, number> = new Map();
  private sessionManager: SessionManager;
  private assignmentMutex = new Mutex();
  private timer: Timer;
  private lastUsedAtMarker = 0;
  private lastReleasedDeviceId: string | null = null;
  private readonly mcpSessionAutolockMap: Map<string, string> = new Map();
  private readonly refreshMissingDeviceMisses: Map<string, number> = new Map();
  private readonly suppressedAutoStartDeviceImageKeys: Set<string> = new Set();
  private daemonSessionId: string;
  private installedAppsRepository: InstalledAppsStore;
  private deviceManager: PlatformDeviceManager;
  private readonly retryExecutor: RetryExecutor;
  private readonly deviceSessionRepository: DeviceSessionRepository;
  private readonly criteriaMatcher: DeviceCriteriaMatcher;
  private readonly releaseSessionForDisconnectedDevice: DeviceDisconnectSessionReleaser;
  private readonly onDeviceReady: DeviceReadyListener | undefined;

  // Max consecutive errors before marking device as failed
  private readonly MAX_DEVICE_ERRORS = 5;
  private readonly REFRESH_MISSING_DEVICE_MISS_THRESHOLD = 2;

  // Device wait configuration for parallel test execution
  private readonly DEVICE_WAIT_TIMEOUT_MS = 60000; // 60 seconds max wait
  private readonly DEVICE_WAIT_INTERVAL_MS = 1000; // Check every 1 second

  constructor(
    sessionManager: SessionManager,
    daemonSessionId: string,
    timer: Timer = defaultTimer,
    installedAppsRepository?: InstalledAppsStore,
    deviceManager: PlatformDeviceManager = new MultiPlatformDeviceManager(),
    retryExecutor: RetryExecutor = defaultRetryExecutor,
    deviceSessionRepository: DeviceSessionRepository = new DeviceSessionRepository(),
    criteriaMatcher: DeviceCriteriaMatcher = new DeviceCriteriaMatcher(),
    releaseSessionForDisconnectedDevice?: DeviceDisconnectSessionReleaser,
    onDeviceReady?: DeviceReadyListener
  ) {
    this.sessionManager = sessionManager;
    this.daemonSessionId = daemonSessionId;
    this.timer = timer;
    this.installedAppsRepository = installedAppsRepository ?? new InstalledAppsRepository();
    this.deviceManager = deviceManager;
    this.retryExecutor = retryExecutor;
    this.deviceSessionRepository = deviceSessionRepository;
    this.criteriaMatcher = criteriaMatcher;
    this.onDeviceReady = onDeviceReady;
    this.releaseSessionForDisconnectedDevice = releaseSessionForDisconnectedDevice ?? (async (
      sessionId,
      _deviceId,
      releaseReason
    ) => {
      await this.sessionManager.releaseSession(sessionId, releaseReason);
    });

    // Free autolocked devices when their session expires (idle timeout auto-release).
    this.sessionManager.onSessionRelease((sessionId, deviceId) => {
      this.releaseAutolockedDevice(sessionId, deviceId);
    });
  }

  /**
   * Initialize pool with available devices
   *
   * Call this once after daemon starts to populate the device list.
   * Typically gets devices from --device-list or by querying emulator status.
   */
  async initializeWithDevices(devices: BootedDevice[]): Promise<void> {
    const now = this.seedLastUsedAt(this.timer.now());
    const perf = createGlobalPerformanceTracker();

    perf.startOperation("populatePool");
    for (const device of devices) {
      this.clearAutoStartSuppressionForBootedDevice(device);
      this.devices.set(device.deviceId, {
        id: device.deviceId,
        name: device.name,
        platform: device.platform,
        sessionId: null,
        status: "idle",
        lastUsedAt: now,
        assignmentCount: 0,
        errorCount: 0,
        iosVersion: device.iosVersion,
        simulatorType: this.criteriaMatcher.getBootedDeviceSimulatorType(device),
      });
      this.deviceSessionStarts.set(device.deviceId, now);
      await this.setDeviceSessionTracking(device.deviceId, now);
    }
    perf.endOperation("populatePool");

    logger.info(`Device pool initialized with ${devices.length} devices`);
  }

  /**
   * Refresh device pool by discovering connected devices
   *
   * Automatically called when pool is empty and a session requests a device.
   * This handles race conditions during daemon startup where device discovery
   * may not have completed before tests begin.
   *
   * Adds newly booted devices and prunes unassigned devices that are no longer
   * booted. Assigned devices are kept so active sessions can be cancelled and
   * released by the disconnect monitor.
   */
  async refreshDevices(): Promise<number> {
    const startTime = this.timer.now();
    const perf = createGlobalPerformanceTracker();
    try {
      logger.info("Refreshing device pool - discovering connected devices...");

      // Log environment for debugging CI issues
      const androidHome = process.env.ANDROID_HOME || "(not set)";
      const androidSdkRoot = process.env.ANDROID_SDK_ROOT || "(not set)";
      logger.info(`Environment: ANDROID_HOME=${androidHome}, ANDROID_SDK_ROOT=${androidSdkRoot}`);

      perf.startOperation("deviceDiscovery");
      const discovery = await this.deviceManager.getBootedDevicesDetailed("either");
      perf.endOperation("deviceDiscovery");
      const bootedDevices = discovery.devices;
      const discoveryTime = this.timer.now() - startTime;
      logger.info(`Device discovery completed in ${discoveryTime}ms, found ${bootedDevices.length} devices`);

      const now = this.seedLastUsedAt(this.timer.now());
      let addedCount = 0;
      let removedCount = 0;
      const bootedDeviceIds = new Set(bootedDevices.map(device => device.deviceId));
      const bootedPlatforms = new Set(bootedDevices.map(device => device.platform));

      perf.startOperation("poolUpdate");
      removedCount = await this.removeDevicesMissingFrom(
        bootedDeviceIds,
        bootedPlatforms,
        discovery.succeededPlatforms
      );

      for (const device of bootedDevices) {
        this.clearAutoStartSuppressionForBootedDevice(device);
        const pooledDevice = this.devices.get(device.deviceId);
        if (!pooledDevice) {
          this.devices.set(device.deviceId, {
            id: device.deviceId,
            name: device.name,
            platform: device.platform,
            sessionId: null,
            status: "idle",
            lastUsedAt: now,
            assignmentCount: 0,
            errorCount: 0,
            iosVersion: device.iosVersion,
            simulatorType: this.criteriaMatcher.getBootedDeviceSimulatorType(device),
          });
          this.deviceSessionStarts.set(device.deviceId, now);
          this.refreshMissingDeviceMisses.delete(device.deviceId);
          await this.setDeviceSessionTracking(device.deviceId, now);
          addedCount++;
          logger.info(`Added device ${device.deviceId} to pool during refresh`);
        } else {
          pooledDevice.name = device.name;
          pooledDevice.platform = device.platform;
          pooledDevice.iosVersion = device.iosVersion;
        }
        this.notifyDeviceReady(device.deviceId);
      }
      perf.endOperation("poolUpdate");

      if (addedCount > 0 || removedCount > 0) {
        logger.info(
          `Device pool refreshed: added ${addedCount}, removed ${removedCount} ` +
          `(total: ${this.devices.size})`
        );
      } else if (bootedDevices.length === 0) {
        logger.warn("No devices found during pool refresh. Is an emulator running?");
        logger.warn("Ensure 'adb devices' returns connected devices in the daemon process environment.");
      } else {
        logger.debug(`Device pool refresh: all ${bootedDevices.length} devices already in pool`);
      }

      return addedCount;
    } catch (error) {
      const elapsed = this.timer.now() - startTime;
      logger.error(`Failed to refresh device pool after ${elapsed}ms: ${error}`);
      if (error instanceof Error) {
        logger.error(`Stack trace: ${error.stack}`);
      }
      return 0;
    }
  }

  /** Notify consumers that a device has reached a boot-ready connection boundary. */
  notifyDeviceReady(deviceId: string): void {
    try {
      this.onDeviceReady?.(deviceId);
    } catch (error) {
      logger.warn(`[DevicePool] Device-ready listener failed for ${deviceId}: ${error}`);
    }
  }

  /**
   * Add a new device to the pool
   */
  async addDevice(device: BootedDevice): Promise<void> {
    this.clearAutoStartSuppressionForBootedDevice(device);
    const existing = this.devices.get(device.deviceId);
    if (existing) {
      // A successful (re)boot of an errored, idle device clears its failure state so
      // criteria autoboot can hand it out instead of failing with "no devices match".
      if (existing.status === "error" && !existing.sessionId) {
        existing.status = "idle";
        existing.errorCount = 0;
        existing.iosVersion = device.iosVersion ?? existing.iosVersion;
        existing.simulatorType = this.criteriaMatcher.getBootedDeviceSimulatorType(device) ?? existing.simulatorType;
        existing.lastUsedAt = this.seedLastUsedAt(this.timer.now());
        logger.info(`Recovered errored device ${device.deviceId} after successful boot`);
      } else {
        logger.warn(`Device ${device.deviceId} already in pool`);
      }
    } else {
      const now = this.seedLastUsedAt(this.timer.now());
      this.devices.set(device.deviceId, {
        id: device.deviceId,
        name: device.name,
        platform: device.platform,
        sessionId: null,
        status: "idle",
        lastUsedAt: now,
        assignmentCount: 0,
        errorCount: 0,
        iosVersion: device.iosVersion,
        simulatorType: this.criteriaMatcher.getBootedDeviceSimulatorType(device),
      });
      this.deviceSessionStarts.set(device.deviceId, now);
      this.refreshMissingDeviceMisses.delete(device.deviceId);
      await this.setDeviceSessionTracking(device.deviceId, now);

      logger.info(`Added device ${device.deviceId} to pool`);
    }

    this.notifyDeviceReady(device.deviceId);
  }

  /**
   * Remove device from pool
   */
  async removeDevice(deviceId: string): Promise<void> {
    const device = this.devices.get(deviceId);
    if (!device) {
      return;
    }

    if (device.sessionId) {
      logger.warn(`Cannot remove device ${deviceId}: assigned to session ${device.sessionId}`);
      return;
    }

    this.devices.delete(deviceId);
    this.deviceSessionStarts.delete(deviceId);
    this.refreshMissingDeviceMisses.delete(deviceId);
    if (this.lastReleasedDeviceId === deviceId) {
      this.lastReleasedDeviceId = null;
    }
    await this.clearDeviceSessionCache(deviceId);
    logger.info(`Removed device ${deviceId} from pool and cleared cached data`);
  }

  async removeDisconnectedDevice(deviceId: string): Promise<void> {
    const device = this.devices.get(deviceId);
    if (device && !device.sessionId) {
      this.suppressAutoStartForDevice(device);
    }
    await this.removeDevice(deviceId);
  }

  private async removeDevicesMissingFrom(
    bootedDeviceIds: Set<string>,
    bootedPlatforms: Set<Platform>,
    succeededPlatforms: Set<Platform>
  ): Promise<number> {
    let removedCount = 0;

    for (const device of Array.from(this.devices.values())) {
      if (bootedDeviceIds.has(device.id)) {
        this.refreshMissingDeviceMisses.delete(device.id);
        continue;
      }
      if (device.sessionId) {
        logger.warn(
          `Device ${device.id} is no longer booted but is assigned to session ${device.sessionId}; keeping until session cleanup`
        );
        continue;
      }
      // Discovery for this platform failed or was unavailable this refresh, so
      // we cannot confirm the device is gone. Retain it rather than pruning a
      // device that may still be running (e.g. iOS simctl failed while Android
      // discovery succeeded, or all tooling was transiently unreachable).
      if (!succeededPlatforms.has(device.platform)) {
        this.refreshMissingDeviceMisses.delete(device.id);
        logger.warn(
          `Device ${device.id} retained: ${device.platform} discovery did not succeed this refresh`
        );
        continue;
      }
      // Discovery succeeded but returned no devices for this platform at all.
      // Tolerate brief reboot/boot races with a small consecutive-miss threshold
      // before removing.
      if (!bootedPlatforms.has(device.platform)) {
        const misses = (this.refreshMissingDeviceMisses.get(device.id) ?? 0) + 1;
        this.refreshMissingDeviceMisses.set(device.id, misses);
        logger.warn(
          `Device ${device.id} missing from ${device.platform} refresh discovery ` +
          `(miss ${misses}/${this.REFRESH_MISSING_DEVICE_MISS_THRESHOLD}); retaining until confirmed`
        );
        if (misses < this.REFRESH_MISSING_DEVICE_MISS_THRESHOLD) {
          continue;
        }
      }

      await this.removeDevice(device.id);
      removedCount++;
    }

    return removedCount;
  }

  /**
   * Assign multiple devices to sessions upfront with a shared timeout
   *
   * This is used for multi-device plans where we want to allocate all devices
   * before execution begins, ensuring we fail fast if not enough devices are available.
   *
   * @param sessionIds Array of session IDs to assign devices to
   * @param timeoutMs Total timeout in milliseconds for allocating ALL devices (default: 5 minutes)
   * @returns Map of sessionId -> deviceId for all assigned devices
   * @throws ActionableError if unable to allocate all devices within timeout
   */
  async assignMultipleDevices(
    sessionIds: string[],
    timeoutMs: number = 300000,
    platform?: Platform
  ): Promise<Map<string, string>> {
    const startTime = this.timer.now();
    const assignments = new Map<string, string>();
    const requiredCount = sessionIds.length;

    logger.info(
      `[DevicePool] Starting upfront allocation of ${requiredCount} devices ` +
      `(timeout: ${timeoutMs / 1000}s)`
    );

    // Validate we have enough devices
    await this.ensurePoolRefreshed();
    const preallocationCandidates = this.getDevicesByPlatform(platform);
    await this.pruneStaleIdleIosDevices(preallocationCandidates);
    await this.evictUnavailableIdleDevicesMatching(device => !platform || device.platform === platform);
    let stats = this.getStatsForPlatform(platform);

    if (stats.total < requiredCount) {
      const started = await this.startAdditionalDevices(requiredCount - stats.total, platform);
      if (started > 0) {
        await this.refreshDevices();
        stats = this.getStatsForPlatform(platform);
      }
    }

    if (stats.total < requiredCount) {
      throw new ActionableError(
        `Not enough devices in pool: need ${requiredCount}, have ${stats.total}.\n` +
        `Device pool status:\n` +
        `  Total devices: ${stats.total}\n` +
        `  Idle: ${stats.idle}\n` +
        `  Assigned: ${stats.assigned}\n` +
        `  Error: ${stats.error}\n\n` +
        `Suggestions:\n` +
        `  - Start ${requiredCount - stats.total} more emulator(s) or simulators\n` +
        `  - Reduce the number of devices required in the test plan\n` +
        `  - Verify ADB is working: adb devices`
      );
    }

    // Try to assign devices with shared timeout using retry executor
    const maxAttempts = Math.ceil(timeoutMs / this.DEVICE_WAIT_INTERVAL_MS);
    const assigned = new Set<string>();
    let firstWaitLogged = false;

    const result = await this.retryExecutor.execute(
      async () => {
        // Try to assign all remaining sessions
        while (assigned.size < requiredCount) {
          const sessionIndex = assigned.size;
          const sessionId = sessionIds[sessionIndex];

          const assignResult = await this.tryAssignDevice(sessionId, platform);

          if (assignResult.success) {
            assigned.add(sessionId);
            assignments.set(sessionId, assignResult.deviceId!);
            logger.info(
              `[DevicePool] Allocated device ${assignResult.deviceId} to session ${sessionId} ` +
              `(${assigned.size}/${requiredCount})`
            );
          } else if (assignResult.livenessUnknown) {
            throw new DevicePoolError(
              `Unable to verify iOS simulator liveness for session ${sessionId}; iOS discovery failed.`,
              false
            );
          } else if (!assignResult.shouldWait) {
            // No devices at all - non-retryable error
            const currentStats = this.getStatsForPlatform(platform);
            throw new DevicePoolError(
              `Failed to allocate devices: no devices available.\n` +
              `Required: ${requiredCount} devices, allocated: ${assigned.size}\n` +
              `Device pool status:\n` +
              `  Total devices: ${currentStats.total}\n` +
              `  Idle: ${currentStats.idle}\n` +
              `  Assigned: ${currentStats.assigned}\n` +
              `  Error: ${currentStats.error}\n\n` +
              `Suggestions:\n` +
              `  - Start an emulator or simulator\n` +
              `  - Check device pool status: auto-mobile --cli listDevices\n` +
              `  - Verify device tooling is working for the selected platform`,
              false
            );
          } else {
            // Devices busy - throw retryable error to wait
            if (!firstWaitLogged) {
              firstWaitLogged = true;
              logger.info(
                `[DevicePool] Waiting for ${requiredCount - assigned.size} more device(s) ` +
                `(${assignResult.totalDevices} total, all currently busy)...`
              );
            }
            throw new DevicePoolError("All devices busy", true);
          }
        }

        // All devices assigned successfully
        return assignments;
      },
      {
        maxAttempts,
        delays: this.DEVICE_WAIT_INTERVAL_MS,
        shouldRetry: error => error instanceof DevicePoolError && error.isRetryable,
      }
    );

    if (!result.success) {
      // Release any devices we've assigned so far
      for (const deviceId of assignments.values()) {
        await this.releaseDevice(deviceId);
      }

      // Check if it was a non-retryable error
      if (result.error instanceof DevicePoolError && !result.error.isRetryable) {
        throw new ActionableError(result.error.message);
      }

      // Timeout case
      const elapsed = this.timer.now() - startTime;
      const currentStats = this.getStatsForPlatform(platform);
      throw new ActionableError(
        `Timed out allocating devices after ${Math.round(elapsed / 1000)}s (${result.attempts} attempts).\n` +
        `Required: ${requiredCount} devices, allocated: ${assigned.size}\n` +
        `Device pool status:\n` +
        `  Total devices: ${currentStats.total}\n` +
        `  Idle: ${currentStats.idle}\n` +
        `  Assigned: ${currentStats.assigned}\n` +
        `  Error: ${currentStats.error}\n\n` +
        `Suggestions:\n` +
        `  - Reduce parallel test count to match available devices\n` +
        `  - Start additional emulators or connect more physical devices\n` +
        `  - Increase device allocation timeout\n` +
        `  - Check if tests are properly releasing devices after completion`
      );
    }

    const totalElapsed = this.timer.now() - startTime;
    logger.info(
      `[DevicePool] Successfully allocated ${requiredCount} devices ` +
      `in ${totalElapsed}ms (${result.attempts} attempts)`
    );

    return result.value!;
  }

  /**
   * Assign multiple devices with per-session criteria.
   *
   * This is used when plans specify device definitions (platform/type/version).
   * When no booted device matches a request, a matching shutdown image may be
   * started before allocation.
   */
  async assignMultipleDevicesByCriteria(
    requests: DeviceAllocationRequest[],
    timeoutMs: number = 300000
  ): Promise<Map<string, string>> {
    const startTime = this.timer.now();
    const assignments = new Map<string, string>();
    const requiredCount = requests.length;

    if (requiredCount === 0) {
      return assignments;
    }

    logger.info(
      `[DevicePool] Starting criteria-based allocation of ${requiredCount} devices ` +
      `(timeout: ${timeoutMs / 1000}s)`
    );

    await this.ensurePoolRefreshed();
    const sortedRequests = this.criteriaMatcher.sortBySpecificity(requests);
    await this.pruneStaleIdleIosDevices(this.getDevicesMatchingAnyRequest(sortedRequests));
    await this.evictUnavailableIdleDevicesMatching(device =>
      sortedRequests.some(request => this.criteriaMatcher.filterDevices([device], request.criteria).length > 0)
    );

    let needsRefresh = false;
    for (const request of sortedRequests) {
      const candidates = this.getDevicesMatchingCriteria(request.criteria);
      if (candidates.length === 0) {
        needsRefresh = true;
        break;
      }
    }

    if (needsRefresh) {
      await this.refreshDevices();
    }

    const started = await this.startAdditionalDevicesForCriteria(sortedRequests);
    if (started > 0) {
      logger.info(`[DevicePool] Started ${started} additional device(s) for criteria-based allocation`);
    }

    for (const request of requests) {
      const candidates = this.getDevicesMatchingCriteria(request.criteria);
      if (candidates.length === 0) {
        const summary = this.criteriaMatcher.formatCriteriaSummary(request.criteria);
        throw new ActionableError(
          `No devices match criteria for session ${request.sessionId}${summary}.\n` +
          `Ensure the required devices are installed, startable, and available.`
        );
      }
    }

    let attemptCount = 0;

    while (assignments.size < requiredCount) {
      attemptCount++;
      const elapsed = this.timer.now() - startTime;

      if (elapsed > timeoutMs) {
        for (const deviceId of assignments.values()) {
          await this.releaseDevice(deviceId);
        }
        throw new ActionableError(
          `Timed out allocating devices after ${Math.round(elapsed / 1000)}s (${attemptCount} attempts).\n` +
          `Required: ${requiredCount} devices, allocated: ${assignments.size}\n` +
          `Suggestions:\n` +
          `  - Boot additional simulators or emulators that match the plan requirements\n` +
          `  - Reduce the number of devices required in the test plan\n` +
          `  - Increase device allocation timeout`
        );
      }

      let assignedThisRound = 0;

      for (const request of sortedRequests) {
        if (assignments.has(request.sessionId)) {
          continue;
        }

        const result = await this.tryAssignDeviceWithCriteria(request.sessionId, request.criteria);

        if (result.success) {
          assignments.set(request.sessionId, result.deviceId!);
          assignedThisRound++;
          logger.info(
            `[DevicePool] Allocated device ${result.deviceId} to session ${request.sessionId} ` +
            `(${assignments.size}/${requiredCount})`
          );
        } else if (result.livenessUnknown) {
          for (const deviceId of assignments.values()) {
            await this.releaseDevice(deviceId);
          }
          throw new ActionableError(
            `Unable to verify iOS simulator liveness for session ${request.sessionId}; iOS discovery failed.`
          );
        } else if (!result.shouldWait) {
          for (const deviceId of assignments.values()) {
            await this.releaseDevice(deviceId);
          }
          const summary = this.criteriaMatcher.formatCriteriaSummary(request.criteria);
          throw new ActionableError(
            `Failed to allocate device for session ${request.sessionId}${summary}.\n` +
            `No matching devices are currently available.\n` +
            `Suggestions:\n` +
            `  - Boot a simulator or emulator that matches the requested criteria\n` +
            `  - Wait for a device to become idle\n` +
            `  - Reduce parallel test count to match available devices`
          );
        }
      }

      if (assignments.size >= requiredCount) {
        break;
      }

      if (assignedThisRound === 0) {
        if (attemptCount === 1) {
          logger.info(`[DevicePool] Waiting for matching devices to become available...`);
        }
        await this.timer.sleep(this.DEVICE_WAIT_INTERVAL_MS);
      }
    }

    const totalElapsed = this.timer.now() - startTime;
    logger.info(
      `[DevicePool] Successfully allocated ${requiredCount} devices by criteria ` +
      `in ${totalElapsed}ms (${attemptCount} attempts)`
    );

    return assignments;
  }

  private async startAdditionalDevices(requiredCount: number, platform?: Platform): Promise<number> {
    if (!platform || requiredCount <= 0) {
      return 0;
    }

    try {
      const candidates = await this.getStartableDeviceImageCandidates(platform);
      if (candidates.length === 0) {
        return 0;
      }

      const toStart = candidates.slice(0, requiredCount);
      let started = 0;

      for (const device of toStart) {
        const label = device.deviceId ?? device.name;
        logger.info(`[DevicePool] Starting additional ${device.platform} device ${label}`);
        const childProcess = await this.deviceManager.startDevice(device);
        const ready = this.criteriaMatcher.withDeviceImageMetadata(
          await waitForDeviceReadyOrCancel(this.deviceManager, device, childProcess),
          device
        );
        await this.addDevice(ready);
        this.trackStartedDeviceProcess(ready, childProcess);
        started++;
      }

      return started;
    } catch (error) {
      logger.warn(`[DevicePool] Failed to start additional devices: ${error}`);
      return 0;
    }
  }

  private async startAdditionalDevicesForCriteria(requests: DeviceAllocationRequest[]): Promise<number> {
    const reservedDeviceIds = new Set<string>();
    const excludedImageIds = new Set<string>();
    let started = 0;

    for (const request of requests) {
      const existing = this.getDevicesMatchingCriteria(request.criteria)
        .find(device => device.status !== "error" && !reservedDeviceIds.has(device.id));
      if (existing) {
        reservedDeviceIds.add(existing.id);
        continue;
      }

      const startedDevice = await this.startAdditionalDeviceMatchingCriteria(
        request.criteria,
        excludedImageIds
      );
      if (startedDevice) {
        reservedDeviceIds.add(startedDevice.id);
        started++;
      }
    }

    return started;
  }

  private async startAdditionalDeviceMatchingCriteria(
    criteria: DeviceAllocationCriteria | undefined,
    excludedImageIds: Set<string>
  ): Promise<PooledDevice | null> {
    if (!criteria?.platform) {
      return null;
    }

    try {
      const candidates = await this.getStartableDeviceImageCandidates(
        criteria.platform,
        criteria,
        excludedImageIds
      );
      const device = candidates[0];
      if (!device) {
        return null;
      }

      const label = device.deviceId ?? device.name;
      logger.info(`[DevicePool] Starting ${device.platform} device ${label} for criteria ${this.criteriaMatcher.formatCriteriaSummary(criteria)}`);
      excludedImageIds.add(this.criteriaMatcher.getDeviceImageKey(device));
      const childProcess = await this.deviceManager.startDevice(device);
      const ready = this.criteriaMatcher.withDeviceImageMetadata(
        await waitForDeviceReadyOrCancel(this.deviceManager, device, childProcess),
        device
      );
      await this.addDevice(ready);
      this.trackStartedDeviceProcess(ready, childProcess);
      return this.devices.get(ready.deviceId) ?? null;
    } catch (error) {
      logger.warn(`[DevicePool] Failed to start device for criteria ${this.criteriaMatcher.formatCriteriaSummary(criteria)}: ${error}`);
      return null;
    }
  }

  private async getStartableDeviceImageCandidates(
    platform: Platform,
    criteria?: DeviceAllocationCriteria,
    excludedImageIds: Set<string> = new Set()
  ): Promise<DeviceInfo[]> {
    const availableImages = await this.deviceManager.listDeviceImages(platform);
    if (availableImages.length === 0) {
      return [];
    }

    const bootedDevices = await this.deviceManager.getBootedDevices(platform);
    const bootedIds = new Set(bootedDevices.map(device => device.deviceId));
    const candidates: DeviceInfo[] = [];

    for (const image of availableImages) {
      if (!this.criteriaMatcher.deviceImageMatchesCriteria(image, criteria)) {
        continue;
      }
      if (!this.criteriaMatcher.isStartableDeviceImage(image)) {
        continue;
      }
      if (excludedImageIds.has(this.criteriaMatcher.getDeviceImageKey(image))) {
        continue;
      }
      if (this.suppressedAutoStartDeviceImageKeys.has(this.criteriaMatcher.getDeviceImageKey(image))) {
        continue;
      }
      if (image.deviceId && bootedIds.has(image.deviceId)) {
        continue;
      }
      const running = image.isRunning === true
        ? true
        : await this.deviceManager.isDeviceImageRunning(image);
      if (running) {
        continue;
      }
      candidates.push(image);
    }

    return candidates;
  }

  /**
   * Ensure device pool has been refreshed at least once
   */
  private async ensurePoolRefreshed(): Promise<void> {
    if (this.devices.size === 0) {
      logger.info("[DevicePool] Pool is empty, attempting auto-refresh...");
      await this.refreshDevices();
    }
  }

  private seedLastUsedAt(now: number): number {
    if (now > this.lastUsedAtMarker) {
      this.lastUsedAtMarker = now;
    }
    return this.lastUsedAtMarker;
  }

  private nextLastUsedAt(): number {
    const now = this.timer.now();
    if (now <= this.lastUsedAtMarker) {
      this.lastUsedAtMarker += 1;
      return this.lastUsedAtMarker;
    }
    this.lastUsedAtMarker = now;
    return now;
  }

  private async evictUnavailableIdleDevicesMatching(matches: (device: PooledDevice) => boolean): Promise<number> {
    let evicted = 0;
    for (const device of Array.from(this.devices.values())) {
      if (device.status !== "idle" || !matches(device)) {
        continue;
      }
      if (!await this.ensurePooledDevicePresentForUse(device)) {
        evicted++;
      }
    }
    return evicted;
  }

  private shouldValidatePooledDevicePresence(device: PooledDevice): boolean {
    return device.platform === "android" && consolePortFromSerial(device.id) !== null;
  }

  private async ensurePooledDevicePresentForUse(device: PooledDevice): Promise<boolean> {
    if (!this.shouldValidatePooledDevicePresence(device)) {
      return true;
    }

    resetAdbDeviceListCache();
    const discovery = await this.deviceManager.getBootedDevicesDetailed(device.platform);
    if (!discovery.succeededPlatforms.has(device.platform)) {
      logger.warn(
        `Retaining ${device.id}: ${device.platform} discovery did not succeed during assignment liveness check`
      );
      return true;
    }

    if (discovery.devices.some(booted => booted.deviceId === device.id)) {
      this.refreshMissingDeviceMisses.delete(device.id);
      return true;
    }

    await this.evictMissingPooledDevice(device, "not present in adb devices");
    return false;
  }

  private async evictMissingPooledDevice(device: PooledDevice, reason: string): Promise<void> {
    logger.warn(`Evicting device ${device.id} from pool: ${reason}`);
    if (device.sessionId) {
      await this.releaseSessionForDisconnectedDevice(
        device.sessionId,
        device.id,
        `device-disconnected:${device.id}`
      );
      device.sessionId = null;
    }
    device.status = "idle";
    await this.removeDevice(device.id);
  }

  private trackStartedDeviceProcess(device: BootedDevice, childProcess: ChildProcess | null | undefined): void {
    if (device.platform !== "android" || consolePortFromSerial(device.deviceId) === null) {
      return;
    }
    if (!childProcess || typeof childProcess.once !== "function") {
      return;
    }

    childProcess.once("exit", (code, signal) => {
      void this.evictStartedDeviceAfterProcessExit(device.deviceId, code, signal).catch(error => {
        logger.warn(
          `[DevicePool] Failed to evict ${device.deviceId} after emulator process exit: ${error}`,
          error
        );
      });
    });
  }

  private async evictStartedDeviceAfterProcessExit(
    deviceId: string,
    code: number | null,
    signal: NodeJS.Signals | null
  ): Promise<void> {
    const device = this.devices.get(deviceId);
    if (!device) {
      return;
    }

    await this.evictMissingPooledDevice(
      device,
      `emulator process exited after startup (code=${code ?? "null"}, signal=${signal ?? "null"})`
    );
  }

  private suppressAutoStartForDevice(device: PooledDevice): void {
    this.suppressedAutoStartDeviceImageKeys.add(device.id);
    this.suppressedAutoStartDeviceImageKeys.add(`${device.platform}:${device.name}`);
  }

  private clearAutoStartSuppressionForBootedDevice(device: BootedDevice): void {
    this.suppressedAutoStartDeviceImageKeys.delete(device.deviceId);
    this.suppressedAutoStartDeviceImageKeys.delete(`${device.platform}:${device.name}`);
  }

  /**
   * Assign a device to a session
   *
   * Called when a new session is created or when a session needs to pick a device.
   * Returns the device ID assigned to the session.
   *
   * Uses mutex to ensure atomic device assignment and prevent race conditions
   * when multiple tests run in parallel.
   *
   * Automatically refreshes device pool if empty, handling race conditions during
   * daemon startup where device discovery may not have completed.
   *
   * When all devices are busy, waits with timeout for a device to become available.
   * This enables parallel test execution with limited devices.
   */
  async assignDeviceToSession(sessionId: string, platform?: Platform): Promise<string> {
    const maxAttempts = Math.ceil(this.DEVICE_WAIT_TIMEOUT_MS / this.DEVICE_WAIT_INTERVAL_MS);
    let firstAttemptLogged = false;

    const result = await this.retryExecutor.execute(
      async attempt => {
        // Try to assign device (mutex ensures atomic assignment)
        const assignResult = await this.tryAssignDevice(sessionId, platform);

        if (assignResult.success) {
          if (attempt > 1) {
            logger.info(
              `Device ${assignResult.deviceId} assigned to session ${sessionId} ` +
              `after ${attempt} attempts`
            );
          }
          return assignResult.deviceId!;
        }

        // No device available - check if we should wait or fail
        if (assignResult.livenessUnknown) {
          throw new DevicePoolError(
            `Unable to verify iOS simulator liveness for session ${sessionId}; iOS discovery failed.`,
            false
          );
        }
        if (assignResult.shouldWait) {
          // Devices exist but are busy - throw retryable error
          if (!firstAttemptLogged) {
            firstAttemptLogged = true;
            logger.info(
              `All ${assignResult.totalDevices} devices busy, ` +
              `session ${sessionId} waiting for availability (timeout: ${this.DEVICE_WAIT_TIMEOUT_MS / 1000}s)...`
            );
          }
          throw new DevicePoolError("All devices busy", true);
        } else {
          // No devices at all - fail immediately with non-retryable error
          const stats = this.getStatsForPlatform(platform);
          throw new DevicePoolError(
            `No devices in pool to assign to session ${sessionId}.\n` +
            `Device pool status:\n` +
            `  Total devices: ${stats.total}\n` +
            `  Idle: ${stats.idle}\n` +
            `  Assigned: ${stats.assigned}\n` +
            `  Error: ${stats.error}\n\n` +
            `Suggestions:\n` +
            `  - Start an emulator or connect a physical device\n` +
            `  - Check device pool status: auto-mobile --cli listDevices\n` +
            `  - Verify device tooling is working for the selected platform`,
            false
          );
        }
      },
      {
        maxAttempts,
        delays: this.DEVICE_WAIT_INTERVAL_MS,
        shouldRetry: error => error instanceof DevicePoolError && error.isRetryable,
      }
    );

    if (!result.success) {
      // Check if it was a non-retryable error (no devices)
      if (result.error instanceof DevicePoolError && !result.error.isRetryable) {
        throw new ActionableError(result.error.message);
      }
      // Timeout case - all attempts exhausted
      const stats = this.getStatsForPlatform(platform);
      throw new ActionableError(
        `Timed out waiting for device after ${Math.round(this.DEVICE_WAIT_TIMEOUT_MS / 1000)}s (${result.attempts} attempts).\n` +
        `Session: ${sessionId}\n` +
        `Device pool status:\n` +
        `  Total devices: ${stats.total}\n` +
        `  Idle: ${stats.idle}\n` +
        `  Assigned: ${stats.assigned}\n` +
        `  Error: ${stats.error}\n\n` +
        `Suggestions:\n` +
        `  - Reduce parallel test count to match available devices\n` +
        `  - Start additional emulators or connect more physical devices\n` +
        `  - Check if tests are properly releasing devices after completion`
      );
    }

    return result.value!;
  }

  /**
   * Try to assign a device to a session (single attempt)
   *
   * Returns success status and whether caller should wait and retry.
   */
  private async tryAssignDevice(sessionId: string, platform?: Platform): Promise<{
    success: boolean;
    deviceId?: string;
    shouldWait: boolean;
    totalDevices: number;
    livenessUnknown?: boolean;
  }> {
    return this.tryAssignFrom(
      sessionId,
      () => this.getDevicesByPlatform(platform),
      "platform pool empty"
    );
  }

  private async tryAssignDeviceWithCriteria(
    sessionId: string,
    criteria?: DeviceAllocationCriteria
  ): Promise<{
    success: boolean;
    deviceId?: string;
    shouldWait: boolean;
    totalDevices: number;
    livenessUnknown?: boolean;
  }> {
    return this.tryAssignFrom(
      sessionId,
      () => this.getDevicesMatchingCriteria(criteria),
      "criteria pool empty"
    );
  }

  /**
   * Shared single-attempt assignment body for platform- and criteria-based
   * allocation. Parameterized only by how candidate devices are selected and
   * the label used when the candidate pool is empty.
   *
   * Selection order: prefer the most recently released device for reuse, then
   * fall back to the least-recently-used idle device for load distribution.
   *
   * @param emptyCandidatePoolReason label logged when candidates exist in the
   *   pool overall but none match this selector (the `totalDevices === 0` case)
   */
  private async tryAssignFrom(
    sessionId: string,
    selectCandidates: () => PooledDevice[],
    emptyCandidatePoolReason: string
  ): Promise<{
    success: boolean;
    deviceId?: string;
    shouldWait: boolean;
    totalDevices: number;
    livenessUnknown?: boolean;
  }> {
    return await this.assignmentMutex.runExclusive(async () => {
      let candidates = selectCandidates();
      let totalDevices = candidates.length;
      let livenessUnknown = false;

      let selection = await this.selectAssignableIdleDevice(candidates);
      let device = selection.device;
      livenessUnknown ||= selection.livenessUnknown;
      if (!device) {
        candidates = selectCandidates();
        totalDevices = candidates.length;
      }

      // If no devices available and pool is empty, try to refresh
      // This handles race conditions during daemon startup
      const busyDevicesBeforeRefresh = candidates.filter(d => d.status === "busy").length;
      if (!device && (this.devices.size === 0 || totalDevices === 0 || busyDevicesBeforeRefresh === 0)) {
        const refreshReason = this.devices.size === 0
          ? "empty pool"
          : totalDevices === 0
            ? emptyCandidatePoolReason
            : "no idle usable devices";
        logger.info(`[DevicePool] Auto-refreshing devices due to ${refreshReason}...`);
        await this.refreshDevices();
        candidates = selectCandidates();
        totalDevices = candidates.length;
        selection = await this.selectAssignableIdleDevice(candidates);
        device = selection.device;
        livenessUnknown ||= selection.livenessUnknown;
        if (!device) {
          candidates = selectCandidates();
          totalDevices = candidates.length;
        }
      }

      if (!device) {
        // No idle device - check if devices exist but are busy
        const busyDevices = candidates.filter(
          d => d.status === "busy"
        ).length;

        return {
          success: false,
          shouldWait: busyDevices > 0, // Wait if devices are busy, fail if none exist
          totalDevices,
          livenessUnknown,
        };
      }

      // Assign to session
      device.sessionId = sessionId;
      device.status = "busy";
      device.lastUsedAt = this.nextLastUsedAt();
      device.assignmentCount++;
      device.errorCount = 0; // Reset errors on successful assignment

      // Create session in SessionManager
      await this.sessionManager.createSession(sessionId, device.id, device.platform);

      logger.info(`Assigned device ${device.id} to session ${sessionId}`);

      return {
        success: true,
        deviceId: device.id,
        shouldWait: false,
        totalDevices,
      };
    });
  }

  private async selectAssignableIdleDevice(candidates: PooledDevice[]): Promise<AssignableIdleDeviceSelection> {
    const iosLiveness = candidates.some(device => device.status === "idle" && device.platform === "ios")
      ? await this.getIosLivenessSnapshot()
      : undefined;
    let device = this.selectIdleDevice(candidates);
    let livenessUnknown = false;

    while (device) {
      const skippedDeviceId = device.id;
      if (this.shouldValidatePooledDevicePresence(device)) {
        if (await this.ensurePooledDevicePresentForUse(device)) {
          return { device, livenessUnknown };
        }
        candidates = candidates.filter(candidate => candidate.id !== skippedDeviceId);
        device = this.selectIdleDevice(candidates);
        continue;
      }

      const status = this.getIdleDeviceLivenessStatus(device, iosLiveness);
      if (status === "assignable") {
        return { device, livenessUnknown };
      }

      if (status === "stale") {
        logger.warn(
          `[DevicePool] Removing idle iOS simulator ${device.id}: simctl no longer reports it as booted`
        );
        await this.removeDevice(device.id);
      } else {
        livenessUnknown = true;
        logger.warn(
          `[DevicePool] Cannot assign idle iOS simulator ${device.id}: iOS liveness discovery failed`
        );
      }
      candidates = candidates.filter(candidate => candidate.id !== skippedDeviceId);
      device = this.selectIdleDevice(candidates);
    }

    return { livenessUnknown };
  }

  private selectIdleDevice(candidates: PooledDevice[]): PooledDevice | undefined {
    // Find idle devices and prefer most recently released for reuse
    const idleDevices = candidates.filter(d => d.status === "idle");
    if (idleDevices.length === 0) {
      return undefined;
    }

    if (this.lastReleasedDeviceId) {
      const lastReleased = idleDevices.find(d => d.id === this.lastReleasedDeviceId);
      if (lastReleased) {
        return lastReleased;
      }
    }

    // Sort by lastUsedAt (ascending) to get least recently used device.
    // This provides better load distribution across devices.
    idleDevices.sort((a, b) => a.lastUsedAt - b.lastUsedAt);
    return idleDevices[0];
  }

  private getDevicesMatchingAnyRequest(requests: DeviceAllocationRequest[]): PooledDevice[] {
    const devicesById = new Map<string, PooledDevice>();
    for (const request of requests) {
      for (const device of this.getDevicesMatchingCriteria(request.criteria)) {
        devicesById.set(device.id, device);
      }
    }
    return Array.from(devicesById.values());
  }

  private async pruneStaleIdleIosDevices(candidates: PooledDevice[]): Promise<number> {
    const iosCandidates = candidates.filter(candidate => {
      const device = this.devices.get(candidate.id);
      return device?.platform === "ios" && device.status === "idle" && !device.sessionId;
    });
    if (iosCandidates.length === 0) {
      return 0;
    }

    const iosLiveness = await this.getIosLivenessSnapshot();
    if (!iosLiveness.discoverySucceeded) {
      logger.warn("[DevicePool] Retaining idle iOS simulators: iOS liveness discovery failed before allocation planning");
      return 0;
    }

    let removedCount = 0;
    for (const candidate of iosCandidates) {
      const device = this.devices.get(candidate.id);
      if (!device) {
        continue;
      }
      if (this.getIdleDeviceLivenessStatus(device, iosLiveness) === "stale") {
        logger.warn(
          `[DevicePool] Removing idle iOS simulator ${device.id}: simctl no longer reports it as booted`
        );
        await this.removeDevice(device.id);
        removedCount++;
      }
    }
    return removedCount;
  }

  private async getIosLivenessSnapshot(): Promise<IosLivenessSnapshot> {
    const discovery = await this.deviceManager.getBootedDevicesDetailed("ios");
    if (!discovery.succeededPlatforms.has("ios")) {
      return {
        discoverySucceeded: false,
        bootedDeviceIds: new Set(),
      };
    }

    return {
      discoverySucceeded: true,
      bootedDeviceIds: new Set(discovery.devices.map(booted => booted.deviceId)),
    };
  }

  private getIdleDeviceLivenessStatus(
    device: PooledDevice,
    iosLiveness: IosLivenessSnapshot | undefined
  ): IdleDeviceLivenessStatus {
    if (device.platform !== "ios") {
      return "assignable";
    }

    if (!iosLiveness?.discoverySucceeded) {
      return "unknown";
    }

    if (iosLiveness.bootedDeviceIds.has(device.id)) {
      return "assignable";
    }

    return "stale";
  }

  private async assertIdleDeviceAssignable(device: PooledDevice, unavailableMessage: string): Promise<void> {
    if (device.status !== "idle" || device.sessionId) {
      return;
    }

    const iosLiveness = device.platform === "ios" ? await this.getIosLivenessSnapshot() : undefined;
    const status = this.getIdleDeviceLivenessStatus(device, iosLiveness);
    if (status === "assignable") {
      return;
    }

    if (status === "stale") {
      logger.warn(
        `[DevicePool] Removing idle iOS simulator ${device.id}: simctl no longer reports it as booted`
      );
      await this.removeDevice(device.id);
      throw new ActionableError(unavailableMessage);
    }

    throw new ActionableError(
      `Unable to verify iOS simulator '${device.id}' is still booted before assignment.\n` +
      `iOS simulator discovery failed, so AutoMobile did not assign this pooled UDID.`
    );
  }

  /**
   * Release device from session
   *
   * Called when a session completes or times out.
   * Frees the device so it can be assigned to other sessions.
   */
  async releaseDevice(deviceId: string): Promise<void> {
    const device = this.devices.get(deviceId);
    if (!device) {
      logger.warn(`Cannot release device ${deviceId}: not in pool`);
      return;
    }

    if (!device.sessionId) {
      logger.debug(`Device ${deviceId} is already idle`);
      return;
    }

    const sessionId = device.sessionId;
    device.sessionId = null;
    device.status = "idle";
    device.errorCount = 0;
    this.lastReleasedDeviceId = deviceId;

    logger.info(`Released device ${deviceId} from session ${sessionId}`);
  }

  /**
   * Bind a known device to a session without running the pool's idle-device
   * selection. If the device is already bound to a live session, reuse that
   * session so repeated startDevice calls stay idempotent.
   */
  async bindOrReuseDeviceSession(sessionId: string, deviceId: string, platform: Platform): Promise<string> {
    return await this.assignmentMutex.runExclusive(async () => {
      const alreadyPooled = this.devices.has(deviceId);
      if (alreadyPooled) {
        this.notifyDeviceReady(deviceId);
      }
      if (!alreadyPooled) {
        const bootedDevices = await this.deviceManager.getBootedDevices(platform);
        const booted = bootedDevices.find(d => d.deviceId === deviceId);
        if (booted) {
          await this.addDevice(booted);
        }
      }

      const device = this.devices.get(deviceId);
      if (!device) {
        throw new ActionableError(`Device '${deviceId}' is not available in the device pool.`);
      }
      await this.assertIdleDeviceAssignable(device, `Device '${deviceId}' is not available in the device pool.`);

      if (!await this.ensurePooledDevicePresentForUse(device)) {
        throw new ActionableError(
          `Device '${deviceId}' is not available in the device pool. ` +
          "It may have been shut down or disconnected."
        );
      }

      if (device.sessionId) {
        const existingSession = this.sessionManager.getSession(device.sessionId);
        if (
          existingSession &&
          existingSession.assignedDevice === deviceId &&
          existingSession.platform === device.platform
        ) {
          const refreshedSession = await this.sessionManager.getOrCreateSession(existingSession.sessionId);
          logger.info(`Reusing existing session ${refreshedSession.sessionId} for device ${deviceId}`);
          return refreshedSession.sessionId;
        }

        if (existingSession) {
          throw new ActionableError(
            `Device '${deviceId}' is already assigned to session ${device.sessionId}.`
          );
        }

        device.sessionId = null;
        device.status = "idle";
      }

      device.sessionId = sessionId;
      device.status = "busy";
      device.lastUsedAt = this.nextLastUsedAt();
      device.assignmentCount++;
      device.errorCount = 0;

      await this.sessionManager.createSession(sessionId, deviceId, platform);
      logger.info(`Bound device ${deviceId} to session ${sessionId}`);
      return sessionId;
    });
  }

  /**
   * Lock a device with an autolock session ID.
   *
   * Generates a new session UUID bound to the device. When autolock is enabled,
   * subsequent tool calls from the same MCP session can resolve this UUID
   * implicitly; other clients must include it explicitly. The session has a
   * configurable idle timeout (AUTO_MOBILE_DEVICE_POOL_TIMEOUT).
   *
   * @param deviceId - The device to lock
   * @param platform - Device platform
   * @returns The generated session ID, or undefined if autolock is disabled
   */
  async autolockDevice(deviceId: string, platform: Platform, mcpSessionId?: string): Promise<string | undefined> {
    if (!isDevicePoolAutolockEnabled()) {
      return undefined;
    }

    const sessionId = randomUUID();

    // Ensure device is in the pool (it may have been freshly booted)
    const alreadyPooled = this.devices.has(deviceId);
    if (alreadyPooled) {
      this.notifyDeviceReady(deviceId);
    }
    if (!alreadyPooled) {
      const bootedDevices = await this.deviceManager.getBootedDevices(platform);
      const booted = bootedDevices.find(d => d.deviceId === deviceId);
      if (booted) {
        await this.addDevice(booted);
      }
    }

    // Assign the device to the generated session
    const device = this.devices.get(deviceId);
    if (!device) {
      throw new ActionableError(
        `Device '${deviceId}' is not available for autolock.\n` +
        `The device may have been shut down or disconnected.\n\n` +
        `Options:\n` +
        `  - Use 'startDevice' with the same criteria to boot a new device\n` +
        `  - Use 'startDevice' with deviceId to restart this specific device\n` +
        `  - Use 'listDevices' to see currently available devices`
      );
    }
    await this.assertIdleDeviceAssignable(
      device,
      `Device '${deviceId}' is not available for autolock.\n` +
      `The device may have been shut down or disconnected.`
    );

    if (!await this.ensurePooledDevicePresentForUse(device)) {
      throw new ActionableError(
        `Device '${deviceId}' is not available for autolock.\n` +
        `The device may have been shut down or disconnected.\n\n` +
        `Options:\n` +
        `  - Use 'startDevice' with the same criteria to boot a new device\n` +
        `  - Use 'startDevice' with deviceId to restart this specific device\n` +
        `  - Use 'listDevices' to see currently available devices`
      );
    }

    device.sessionId = sessionId;
    device.status = "busy";
    device.lastUsedAt = this.nextLastUsedAt();
    device.assignmentCount++;
    device.autolockSessionId = sessionId;

    const timeoutMs = getDevicePoolTimeoutMs();
    // Autolock clients (CLI/agents) do not send heartbeats, so align the heartbeat
    // timeout with the idle timeout. Otherwise the daemon's heartbeat watchdog
    // (10s default) would reap the lock far sooner than the configured idle timeout.
    // Interactions still bump lastHeartbeat, so an active client stays locked while
    // a truly idle one is released after the idle timeout.
    const session = await this.sessionManager.createSession(sessionId, deviceId, platform, timeoutMs, timeoutMs);
    if (mcpSessionId) {
      this.mcpSessionAutolockMap.set(mcpSessionId, sessionId);
    }
    await this.deviceSessionRepository.markAutolockSession(sessionId, {
      mcpSessionId: mcpSessionId ?? null,
      daemonSessionId: this.daemonSessionId,
      lastUsedAtMs: session.lastUsedAt,
      expiresAtMs: session.expiresAt,
    });
    logger.info(`Autolocked device ${deviceId} with session ${sessionId} (timeout: ${timeoutMs}ms)`);
    return sessionId;
  }

  /**
   * Resolve the autolock session associated with an MCP client session.
   *
   * startDevice binds its generated device-session UUID to the MCP session that
   * called it. Later tool calls from the same MCP session can omit sessionUuid;
   * this lookup restores the device-session UUID while it is still live.
   */
  resolveAutolockSessionForMcpSession(
    mcpSessionId: string | undefined,
    platform?: Platform
  ): string | undefined {
    if (!mcpSessionId) {
      return undefined;
    }

    const sessionId = this.mcpSessionAutolockMap.get(mcpSessionId);
    if (!sessionId) {
      return undefined;
    }

    const session = this.sessionManager.getSession(sessionId);
    if (!session) {
      this.mcpSessionAutolockMap.delete(mcpSessionId);
      return undefined;
    }

    const device = this.devices.get(session.assignedDevice);
    if (!device || device.autolockSessionId !== sessionId) {
      this.mcpSessionAutolockMap.delete(mcpSessionId);
      return undefined;
    }

    if (platform && device.platform !== platform) {
      return undefined;
    }

    return sessionId;
  }

  /**
   * Free a device whose autolock session has been released or has expired.
   *
   * Invoked via the SessionManager release callback. Only acts on devices that
   * were locked by the released session, so non-autolock sessions and devices
   * that have since been re-locked by a different session are left untouched.
   */
  private releaseAutolockedDevice(sessionId: string, deviceId: string): void {
    const device = this.devices.get(deviceId);
    if (!device || device.autolockSessionId !== sessionId) {
      return;
    }

    device.sessionId = null;
    device.status = "idle";
    device.errorCount = 0;
    device.autolockSessionId = undefined;
    this.lastReleasedDeviceId = deviceId;
    this.clearMcpAutolockMappings(sessionId);

    logger.info(`Autolock idle timeout: released device ${deviceId} from session ${sessionId}`);
  }

  private clearMcpAutolockMappings(sessionId: string): void {
    for (const [mcpSessionId, mappedSessionId] of this.mcpSessionAutolockMap) {
      if (mappedSessionId === sessionId) {
        this.mcpSessionAutolockMap.delete(mcpSessionId);
      }
    }
  }

  /**
   * Assert that a session is permitted to interact with a device.
   *
   * When autolock is enabled and a device is locked to a session, only that
   * session UUID may drive it. A mismatched or absent session UUID is rejected.
   * No-op when autolock is disabled or the device is not locked.
   */
  assertAutolockAccess(deviceId: string, sessionUuid: string | undefined): void {
    if (!isDevicePoolAutolockEnabled()) {
      return;
    }

    const device = this.devices.get(deviceId);
    if (!device || !device.autolockSessionId) {
      return;
    }

    if (device.autolockSessionId !== sessionUuid) {
      throw new ActionableError(
        `Device '${deviceId}' is locked to another session.\n` +
        `Autolock is enabled, so tool calls must either come from the same MCP session ` +
        `that called 'startDevice' or include the sessionId returned for this device.\n\n` +
        `Options:\n` +
        `  - Pass the sessionId from the 'startDevice' that locked this device\n` +
        `  - Use 'startDevice' to lock a different available device\n` +
        `  - Wait for the idle timeout to release this device`
      );
    }
  }

  /**
   * Mark device as having an error
   *
   * Track consecutive errors. If errors exceed threshold, mark device as failed.
   */
  recordDeviceError(deviceId: string): void {
    const device = this.devices.get(deviceId);
    if (!device) {
      return;
    }

    device.errorCount++;

    if (device.errorCount >= this.MAX_DEVICE_ERRORS) {
      device.status = "error";
      logger.error(
        `Device ${deviceId} marked as error ` +
        `(${device.errorCount} consecutive errors)`
      );
    } else {
      logger.warn(
        `Device ${deviceId} error count: ${device.errorCount}/${this.MAX_DEVICE_ERRORS}`
      );
    }
  }

  /**
   * Clear error count for device (after successful operation)
   */
  clearDeviceError(deviceId: string): void {
    const device = this.devices.get(deviceId);
    if (device) {
      device.errorCount = 0;
    }
  }

  /**
   * Get device by ID
   */
  getDevice(deviceId: string): PooledDevice | null {
    return this.devices.get(deviceId) || null;
  }

  /**
   * Get device assigned to session
   */
  getDeviceForSession(sessionId: string): PooledDevice | null {
    return (
      Array.from(this.devices.values()).find(d => d.sessionId === sessionId) || null
    );
  }

  /**
   * Get all idle devices (available for assignment)
   */
  getIdleDevices(): PooledDevice[] {
    return Array.from(this.devices.values()).filter(d => d.status === "idle");
  }

  /**
   * Get all devices currently assigned to sessions
   */
  getAssignedDevices(): PooledDevice[] {
    return Array.from(this.devices.values()).filter(
      d => d.status === "busy" && d.sessionId !== null
    );
  }

  /**
   * Get all devices in error state
   */
  getErrorDevices(): PooledDevice[] {
    return Array.from(this.devices.values()).filter(d => d.status === "error");
  }

  /**
   * Get count of available devices (can be assigned to new sessions)
   */
  getAvailableDeviceCount(): number {
    return this.getIdleDevices().length;
  }

  /**
   * Get total device count
   */
  getTotalDeviceCount(): number {
    return this.devices.size;
  }

  /**
   * Get all devices in pool
   */
  getAllDevices(): PooledDevice[] {
    return Array.from(this.devices.values());
  }

  private getDevicesMatchingCriteria(criteria?: DeviceAllocationCriteria): PooledDevice[] {
    return this.criteriaMatcher.filterDevices(this.getAllDevices(), criteria);
  }

  private getDevicesByPlatform(platform?: Platform): PooledDevice[] {
    if (!platform) {
      return this.getAllDevices();
    }
    return Array.from(this.devices.values()).filter(device => device.platform === platform);
  }

  private getStatsForPlatform(platform?: Platform): {
    total: number;
    idle: number;
    assigned: number;
    error: number;
  } {
    const devices = this.getDevicesByPlatform(platform);
    const idle = devices.filter(device => device.status === "idle").length;
    const assigned = devices.filter(device => device.status === "busy").length;
    const error = devices.filter(device => device.status === "error").length;

    return {
      total: devices.length,
      idle,
      assigned,
      error,
    };
  }

  /**
   * Get pool statistics for monitoring
   */
  getStats(): {
    total: number;
    idle: number;
    assigned: number;
    error: number;
    avgAssignments: number;
    } {
    const all = this.getAllDevices();
    const idle = this.getIdleDevices().length;
    const assigned = this.getAssignedDevices().length;
    const error = this.getErrorDevices().length;
    const avgAssignments = all.length > 0
      ? Math.round(
        all.reduce((sum, d) => sum + d.assignmentCount, 0) / all.length
      )
      : 0;

    return {
      total: all.length,
      idle,
      assigned,
      error,
      avgAssignments,
    };
  }

  /**
   * Get detailed status report
   */
  getStatusReport(): string {
    const stats = this.getStats();
    const lines = [
      "\n=== Device Pool Status ===",
      `Total Devices: ${stats.total}`,
      `  Idle:       ${stats.idle}`,
      `  Assigned:   ${stats.assigned}`,
      `  Error:      ${stats.error}`,
      `Avg Assignments: ${stats.avgAssignments}`,
      "",
      "Device Details:",
    ];

    for (const device of this.getAllDevices()) {
      const status = device.status === "error" ? "❌" : device.sessionId ? "🔴" : "🟢";
      const session = device.sessionId ? ` (${device.sessionId})` : "";
      lines.push(
        `  ${status} ${device.id}: ${device.status}${session} (${device.assignmentCount} uses, ${device.errorCount} errors)`
      );
    }

    lines.push("=== End Report ===\n");
    return lines.join("\n");
  }

  /**
   * Set session tracking for a device in the installed apps cache
   */
  private async setDeviceSessionTracking(deviceId: string, sessionStart: number): Promise<void> {
    try {
      await this.installedAppsRepository.setSessionTracking(this.daemonSessionId, deviceId, sessionStart);
    } catch (error) {
      logger.warn(`Failed to set session tracking for device ${deviceId}: ${error}`);
    }
  }

  /**
   * Clear installed apps cache for a device session
   */
  private async clearDeviceSessionCache(deviceId: string): Promise<void> {
    try {
      await getInstalledAppsCacheWriteCoordinator().invalidate(deviceId, () =>
        getDbWriteBarrier().track(() =>
          this.installedAppsRepository.clearDeviceSession(deviceId)
        ).then(() => undefined)
      );
      logger.info(`[DevicePool] Cleared installed apps cache for device ${deviceId}`);
    } catch (error) {
      logger.warn(`Failed to clear device session cache for ${deviceId}: ${error}`);
    }
  }
}
