import { afterEach, describe, expect, spyOn, test } from "bun:test";
import WebSocket from "ws";
import response from "../../../fixtures/ios/swipe-deadline-phases.json";
import {
  decodeCtrlProxyMessage,
  gesturePhaseSummary,
} from "../../../../src/features/observe/ios/decodeCtrlProxyMessage";
import { IOSCtrlProxyClient } from "../../../../src/features/observe/ios/IOSCtrlProxyClient";
import type { WebSocketMessage } from "../../../../src/features/observe/ios/types";
import { CtrlProxyGestures } from "../../../../src/features/observe/ios/CtrlProxyGestures";
import { RequestManager } from "../../../../src/utils/RequestManager";
import {
  createPerformanceTracker,
  setDebugPerfEnabled,
} from "../../../../src/utils/PerformanceTracker";
import type { PerformanceTracker } from "../../../../src/utils/PerformanceTracker";
import { logger } from "../../../../src/utils/logger";
import { FakeTimer } from "../../../fakes/FakeTimer";
import { createSuccessWebSocketFactory } from "../../../fakes/FakeWebSocket";
import { finalizeToolResponse } from "../../../../src/server/finalizeToolResponse";
import {
  createStructuredToolResponse,
  getStructuredPayload,
  getStructuredField,
} from "../../../../src/utils/toolUtils";
import { SwipeOn } from "../../../../src/features/action/swipeon/SwipeOn";
import type { SwipeOnOptions, SwipeOnResult } from "../../../../src/models";

// Generated by compiling the production Swift PerfTiming/WebSocketResponse models and
// encoding WebSocketResponse.withPerfTiming with JSONEncoder (.sortedKeys/.prettyPrinted).
// This is real encoder output, not a captured simulator response.
const message: WebSocketMessage = response;
const device = { deviceId: "gesture-diagnostics", platform: "ios", name: "Fake iPhone" } as const;

afterEach(() => setDebugPerfEnabled(false));

describe("iOS gesture phase diagnostics", () => {
  test("bound error preserves the running phase without a perf tree", () => {
    const error =
      "Command request_swipe exceeded execution bound 4500ms in phase xcuitestGesture after 4502ms; XCUITest call is still executing and the runner stays busy until it returns";
    expect(
      decodeCtrlProxyMessage({ type: "swipe_result", requestId: "bound", success: false, error })
        ?.result,
    ).toMatchObject({ success: false, error });
  });

  test("real encoder fixture retains children and adds summary to the deadline error", () => {
    const decoded = decodeCtrlProxyMessage(message);
    expect(decoded?.result).toMatchObject({
      success: false,
      perfTiming: message.perfTiming,
      error: `${message.error}; ${gesturePhaseSummary(message.perfTiming)}`,
    });
    expect(gesturePhaseSummary(message.perfTiming)).toContain("xcuitestGestureMs=5200");
    expect(gesturePhaseSummary(undefined)).toBeUndefined();
  });

  test("failed swipe retains runner phases in requested tool timing output", async () => {
    const timer = new FakeTimer();
    const manager = new RequestManager(timer);
    const perf = createPerformanceTracker(true, timer);
    perf.serial("swipeOn");
    const socket = {
      readyState: WebSocket.OPEN,
      send(data: string) {
        const request: { requestId: string } = JSON.parse(data);
        const decoded = decodeCtrlProxyMessage({ ...message, requestId: request.requestId });
        manager.resolve(request.requestId, decoded?.result);
      },
    } as unknown as WebSocket;
    const gestures = new CtrlProxyGestures({
      timer,
      requestManager: manager,
      getWebSocket: () => socket,
      ensureConnected: async () => true,
      cancelScreenshotBackoff() {},
    });
    const result = await gestures.requestSwipe(1, 2, 3, 4, 300, 5000, perf);
    perf.end();
    expect(result.success).toBe(false);
    const finalized = finalizeToolResponse(
      createStructuredToolResponse({
        success: false,
        error: result.error,
        timing: perf.getTimings(),
      }),
      { name: "swipeOn" },
    );
    expect(JSON.stringify(getStructuredPayload(finalized))).toContain('"name":"gesturePhases"');
    expect(getStructuredField(finalized, "timing")).toEqual(perf.getTimings());
    expect(JSON.stringify(getStructuredPayload(finalized))).toContain('"durationMs":5200');
  });

  test("SwipeOn failure catch retains requested timing without a post-gesture observation", async () => {
    setDebugPerfEnabled(true);
    // Exercise the real failure handler with a fake execution boundary; no client/device setup.
    const action = SwipeOn.prototype as unknown as {
      executeLegacy(options: SwipeOnOptions): Promise<SwipeOnResult>;
    };
    const fake = {
      device,
      validateOptions: () => null,
      visionConfig: { enabled: false },
      async executeScreenSwipe(
        _options: SwipeOnOptions,
        _progress: unknown,
        perf: PerformanceTracker,
      ) {
        perf.addExternalTiming("iosPerf", response.perfTiming);
        throw new Error(`${message.error}; ${gesturePhaseSummary(message.perfTiming)}`);
      },
    };
    const result = await action.executeLegacy.call(fake, { direction: "up", autoTarget: false });
    expect(result.success).toBe(false);
    expect(JSON.stringify(result.timing)).toContain('"name":"gesturePhases"');
    const finalized = finalizeToolResponse(createStructuredToolResponse(result), {
      name: "swipeOn",
    });
    expect(getStructuredField(finalized, "timing")).toEqual(result.timing);
    setDebugPerfEnabled(false);
    const withoutTiming = await action.executeLegacy.call(fake, {
      direction: "up",
      autoTarget: false,
    });
    expect(withoutTiming).not.toHaveProperty("timing");
  });

  test("late reply warns with phases after the request timer removed pending state", async () => {
    const timer = new FakeTimer();
    const client = IOSCtrlProxyClient.createForTesting(
      device,
      8765,
      createSuccessWebSocketFactory(timer),
      timer,
    );
    const boundary = client as unknown as {
      requestManager: RequestManager;
      processMessage(message: WebSocketMessage): void;
    };
    const warn = spyOn(logger, "warn").mockImplementation(() => {});
    const debug = spyOn(logger, "debug").mockImplementation(() => {});
    try {
      const pending = boundary.requestManager.register(
        message.requestId ?? "phase-swipe",
        "swipe",
        5000,
        () => ({ success: false, error: "Swipe timed out after 5000ms" }),
      );
      timer.advanceTime(5000);
      await pending;
      warn.mockClear();
      boundary.processMessage(message);
      expect(warn).toHaveBeenCalledTimes(1);
      expect(warn.mock.calls[0]?.[0]).toContain("xcuitestGestureMs=5200");
      expect(warn.mock.calls[0]?.[0]).toContain("lateResponse=true");
      boundary.processMessage({ ...message, perfTiming: undefined });
      expect(warn).toHaveBeenCalledTimes(1);
    } finally {
      warn.mockRestore();
      debug.mockRestore();
      await client.close();
    }
  });

  test("pending failed reply logs its phase summary at debug", async () => {
    const timer = new FakeTimer();
    const client = IOSCtrlProxyClient.createForTesting(
      device,
      8765,
      createSuccessWebSocketFactory(timer),
      timer,
    );
    const boundary = client as unknown as {
      requestManager: RequestManager;
      processMessage(message: WebSocketMessage): void;
    };
    const debug = spyOn(logger, "debug").mockImplementation(() => {});
    try {
      const pending = boundary.requestManager.register(
        message.requestId ?? "phase-swipe",
        "swipe",
        5000,
      );
      boundary.processMessage(message);
      expect(await pending).toMatchObject({ success: false, perfTiming: message.perfTiming });
      expect(
        debug.mock.calls.some(
          ([line]) => typeof line === "string" && line.includes("xcuitestGestureMs=5200"),
        ),
      ).toBe(true);
    } finally {
      debug.mockRestore();
      await client.close();
    }
  });
});
