@testable import AutoMobilePrototypeAgentCore
import XCTest

final class PrototypeScalarTextTests: XCTestCase {
    private let hugeMax =
        "179769313486231570814527423731704356798070567525844996598917476803157260780028538760589558632766878171540458953514382464234321326889464182768467546703537516986049910576551282076245490090389328944075868508455133942304583236903222948165808559332123348274797826204144723168738177180919299881250404026184124858368"

    /// Expected strings generated by the host: `renderScalar(x)` from
    /// `src/features/prototype/prototypeTemplate.ts`, run with `bun -e` on 2026-10-10.
    private var table: [(Double, String)] {
        [
            (0, "0"), (-0.0, "0"), (1, "1"), (-1, "-1"), (100, "100"), (12_345_678, "12345678"),
            (1e20, "100000000000000000000"), (1e21, "1000000000000000000000"),
            (123_456_789_012_345_680_000, "123456789012345683968"),
            (9_007_199_254_740_993, "9007199254740992"),
            (0.1, "0.1"), (0.5, "0.5"), (-0.5, "-0.5"), (0.1 + 0.2, "0.30000000000000004"),
            (0.00001, "0.00001"), (1e-6, "0.000001"), (1e-7, "1e-7"), (1.5e-7, "1.5e-7"),
            (123_456.789, "123456.789"), (1e-300, "1e-300"), (5e-324, "5e-324"),
            (1.7976931348623157e308, hugeMax), (-1.5e-7, "-1.5e-7"), (1e22, "10000000000000000000000"),
            (-1e21, "-1000000000000000000000"), (0.000001234, "0.000001234"), (1.23e-18, "1.23e-18"),
            (4.35, "4.35"),
        ]
    }

    func testEveryNumberRendersAsTheHostDoes() {
        for (value, expected) in table {
            XCTAssertEqual(PrototypeScalarText.render(value), expected, "\(value)")
            XCTAssertEqual(JSONValue.number(value).displayString, expected, "\(value)")
        }
    }

    func testStringsAndBooleansAreUnchanged() {
        XCTAssertEqual(JSONValue.string("a").displayString, "a")
        XCTAssertEqual(JSONValue.bool(true).displayString, "true")
        XCTAssertEqual(JSONValue.bool(false).displayString, "false")
    }

    func testKeyInterpolationAndRepeatBindingGiveTheSameText() throws {
        for (value, expected) in table {
            let keyed = interpolatePrototypeText("{n}", state: ["n": .number(value)], pager: nil)
            let expanded = PrototypeRepeat.expand(.object([
                "type": .string("column"),
                "repeat": .object(["as": .string("row"), "items": .array([.object(["n": .number(value)])])]),
                "children": .array([.object(["type": .string("text"), "text": .string("{row.n}")])]),
            ]))
            guard case let .object(root) = expanded, case let .array(children)? = root["children"],
                  case let .object(child)? = children.first else { return XCTFail("not expanded") }
            XCTAssertEqual(keyed, expected, "\(value)")
            XCTAssertEqual(child["text"], .string(expected), "\(value)")
        }
    }
}
