#!/usr/bin/env bash
#
# Single source of truth for the pinned XcodeGen version *and* the helpers that
# enforce it. Mirrors scripts/ktfmt/ktfmt_version.sh, which solved the same bug
# class for ktfmt (issue #2966).
#
# This file is *sourced* (not executed) by install-xcodegen.sh, xcodegen-generate.sh
# and xcodegen-drift-check.sh so the pin -- and the parse/gate logic around it --
# lives in exactly one place.
#
# Why it must be enforced rather than declared (issue #3975): XcodeGen's generated
# project layout is not stable across releases. 2.45.4 and 2.46.0 order the
# PBXProject `targets` array differently, so a project generated by one version
# reads as drift to the other. CI ran a bare `brew install xcodegen`, which
# resolves against whatever formula index the runner image ships -- that silently
# installed 2.45.4 while contributors had 2.46.0, and every PR failed the drift
# check with an ordering-only diff that looks identical to a genuinely stale
# project file. A skewed generator must fail loudly, before it writes anything.

XCODEGEN_VERSION="2.46.0"

# The vendor's prebuilt release archive. The version is in the URL, so this is
# version-exact by construction -- unlike Homebrew, which cannot install an
# arbitrary older version and drifts whenever its formula moves.
# shellcheck disable=SC2034  # consumed by scripts that source this file
XCODEGEN_RELEASE_URL="https://github.com/yonaskolb/XcodeGen/releases/download/${XCODEGEN_VERSION}/xcodegen.zip"

# GitHub release assets are MUTABLE: a re-uploaded xcodegen.zip under the same
# tag would still report 2.46.0 and sail through the version gate, then generate
# different bytes -- reproducing #3975 with the guard reporting green. Pinning
# the digest is what actually makes this version-exact.
# shellcheck disable=SC2034  # consumed by scripts that source this file
XCODEGEN_RELEASE_SHA256="4d9e34b62172d645eed6457cac13fc222569974098ef4ee9c3368bedf0196806"

# The installer may land in ${HOME}/.local when /usr/local is not writable, and
# a subprocess cannot change its caller's PATH. Without this, an install that
# SUCCEEDS is invisible to the caller's require_pinned gate, which then fails
# telling the user to run the installer that just worked. Mirrors the same
# export in scripts/ktfmt/install_ktfmt.sh.
export PATH="${HOME}/.local/bin:${PATH}"

# Parse the version from `xcodegen --version` (e.g. "Version: 2.46.0"). Prints
# the empty string if xcodegen is absent or emits nothing parseable. Always
# succeeds, so callers need no `|| true` -- which would disable set -e (SC2310).
installed_xcodegen_version() {
    if ! command -v xcodegen >/dev/null 2>&1; then
        return 0
    fi
    xcodegen --version 2>/dev/null | awk '{ gsub(/\r/, ""); print $NF; exit }'
}

# Gate: assert the xcodegen on PATH matches the pin, else print an actionable
# message and `exit 1`. Called before any path that GENERATES project files, so
# a skewed generator fails with both version numbers named instead of producing
# a mystery ordering diff later. Colours are referenced via ${RED:-} so this is
# safe to call before the caller defines them.
require_pinned_xcodegen_version() {
    local found
    found="$(installed_xcodegen_version)"
    if [[ "${found}" == "${XCODEGEN_VERSION}" ]]; then
        return 0
    fi

    echo -e "${RED:-}XcodeGen version mismatch: found '${found:-none}', this repo pins '${XCODEGEN_VERSION}'.${NC:-}" >&2
    echo -e "${RED:-}Generated project layout differs between versions (issue #3975), so this fails loudly instead of writing a skewed project file.${NC:-}" >&2
    echo -e "${RED:-}Install the pinned version: bash scripts/ios/install-xcodegen.sh${NC:-}" >&2
    exit 1
}
