// Writes app-icon.svg: the original-colour AutoMobile truck (passed in via TRUCK_FRAG) fitted
// onto a red "crayon" background on the macOS Big Sur icon grid. Invoked by
// generate-app-icons.sh; BBOX is the truck's content box (WxH+X+Y) in the logo's 400x400 space.
import { writeFileSync } from "node:fs";

const bbox = process.env.BBOX;
const truckFrag = process.env.TRUCK_FRAG;
const outSvg = process.env.OUT_SVG;
if (!bbox || !truckFrag || !outSvg) {
  throw new Error("BBOX, TRUCK_FRAG and OUT_SVG must be set");
}

const parsed = /^(\d+)x(\d+)\+(\d+)\+(\d+)$/.exec(bbox);
if (!parsed) {
  throw new Error(`unexpected bbox format: ${bbox}`);
}
const [w, h, x, y] = parsed.slice(1).map(Number);

// macOS Big Sur grid: 1024 canvas, 824 body inset 100px. Fit the truck to 80% of the body width.
const canvas = 1024;
const bodyWidth = 824;
const targetW = Math.round(bodyWidth * 0.8);
const targetH = Math.round((targetW * h) / w);
const posX = Math.round((canvas - targetW) / 2);
const posY = Math.round((canvas - targetH) / 2);
const viewBox = `${x} ${y} ${w} ${h}`;

const svg = `<?xml version="1.0" encoding="UTF-8"?>
<!--
  GENERATED by scripts/desktop/generate-app-icons.sh - do not edit by hand.

  AutoMobile desktop app icon: the canonical hand-drawn truck from docs/img/logo.svg in its
  original colours (red marker outline, white fill, dark outline tires) overlaid on a red
  "crayon" background. The crayon texture is generated with feTurbulence so the fill reads
  waxy and uneven. Layout follows the macOS Big Sur grid (1024 canvas, 824 rounded body,
  185px radius). Change the background in scripts/desktop/lib/compose-icon.ts or the truck in
  docs/img/logo.svg, then rerun scripts/desktop/generate-app-icons.sh.
-->
<svg xmlns="http://www.w3.org/2000/svg" width="1024" height="1024" viewBox="0 0 1024 1024">
  <defs>
    <clipPath id="bodyClip">
      <rect x="100" y="100" width="824" height="824" rx="185" ry="185"/>
    </clipPath>
    <filter id="crayonStreaks" x="0%" y="0%" width="100%" height="100%">
      <feTurbulence type="fractalNoise" baseFrequency="0.006 0.028" numOctaves="4" seed="7" stitchTiles="stitch" result="noise"/>
      <feColorMatrix in="noise" type="matrix" values="0 0 0 0 0  0 0 0 0 0  0 0 0 0 0  0 0 0 0.85 -0.18" result="mask"/>
      <feComposite in="SourceGraphic" in2="mask" operator="in"/>
    </filter>
    <filter id="crayonMottle" x="0%" y="0%" width="100%" height="100%">
      <feTurbulence type="fractalNoise" baseFrequency="0.015" numOctaves="4" seed="19" stitchTiles="stitch" result="noise"/>
      <feColorMatrix in="noise" type="matrix" values="0 0 0 0 0  0 0 0 0 0  0 0 0 0 0  0 0 0 0.9 -0.32" result="mask"/>
      <feComposite in="SourceGraphic" in2="mask" operator="in"/>
    </filter>
    <linearGradient id="sheen" x1="0" y1="100" x2="0" y2="924" gradientUnits="userSpaceOnUse">
      <stop offset="0" stop-color="#ffffff" stop-opacity="0.12"/>
      <stop offset="0.5" stop-color="#ffffff" stop-opacity="0"/>
      <stop offset="1" stop-color="#000000" stop-opacity="0.10"/>
    </linearGradient>
    <filter id="truckShadow" x="-15%" y="-15%" width="130%" height="130%">
      <feDropShadow dx="0" dy="10" stdDeviation="12" flood-color="#5a0f0a" flood-opacity="0.35"/>
    </filter>
  </defs>

  <g clip-path="url(#bodyClip)">
    <rect x="100" y="100" width="824" height="824" fill="#c62a22"/>
    <rect x="100" y="100" width="824" height="824" fill="#f4746a" opacity="0.5" filter="url(#crayonStreaks)"/>
    <rect x="100" y="100" width="824" height="824" fill="#ef6459" opacity="0.42" filter="url(#crayonMottle)"/>
    <rect x="100" y="100" width="824" height="824" fill="url(#sheen)"/>
  </g>

  <svg x="${posX}" y="${posY}" width="${targetW}" height="${targetH}" viewBox="${viewBox}" preserveAspectRatio="xMidYMid meet">
    <g filter="url(#truckShadow)">${truckFrag}</g>
  </svg>
</svg>
`;

writeFileSync(outSvg, svg);
